import { mkdirSync, rmSync, writeFileSync } from 'fs';

import { Fraction } from './utils/fraction';

// const template = (x: string, y: string) =>
// 	`

// 'VECTRIC POST REVISION
// '90F96787DA0D140DD9CF843C14DAE4D8
// '----------------------------------------------------------------
// 'SHOPBOT ROUTER FILE IN INCHES
// 'GENERATED BY PARTWorks
// 'Minimum extent in X = 0.000 Minimum extent in Y = 0.000 Minimum extent in Z = -1.000
// 'Maximum extent in X = 12.500 Maximum extent in Y = 6.625 Maximum extent in Z = 0.000
// 'Length of material in X = 12.500
// 'Length of material in Y = 6.625
// 'Depth of material in Z = 1.000
// 'Home Position Information = Bottom Left Corner, Material Surface
// 'Home X = 0.000000 Home Y = 0.000000 Home Z = 0.800000
// 'Rapid clearance gap or Safe Z = 0.200
// 'UNITS:Inches
// '
// IF %(25)=1 THEN GOTO UNIT_ERROR	'check to see software is set to standard
// SA                             	'Set program to absolute coordinate mode
// CN, 90
// 'New Path
// 'Toolpath Name = Profile 1 [1]
// 'Tool Name   = Ball Nose (1/2")

// &PWSafeZ = 0.200
// &PWZorigin = Material Surface
// &PWMaterial = 1.000
// '&ToolName = "Ball Nose (1/2")"
// &Tool =8           'Tool number to change to
// C9                   'Change tool
// TR,11000               'Set spindle RPM
// C6                   'Spindle on
// PAUSE 2
// '
// MS,0.5,0.1
// JZ,0.800000
// J3,1.000000,1.000000,0.200000
// M3,1.000000,1.000000,-0.062500
// M3,1.000000,${y},-0.062500
// M3,${x},${y},-0.062500
// M3,${x},1.000000,-0.062500
// M3,1.000000,1.000000,-0.062500
// M3,1.000000,1.000000,-0.125000
// M3,1.000000,${y},-0.125000
// M3,${x},${y},-0.125000
// M3,${x},1.000000,-0.125000
// M3,1.000000,1.000000,-0.125000
// M3,1.000000,1.000000,-0.187500
// M3,1.000000,${y},-0.187500
// M3,${x},${y},-0.187500
// M3,${x},1.000000,-0.187500
// M3,1.000000,1.000000,-0.187500
// M3,1.000000,1.000000,-0.250000
// M3,1.000000,${y},-0.250000
// M3,${x},${y},-0.250000
// M3,${x},1.000000,-0.250000
// M3,1.000000,1.000000,-0.250000
// J3,1.000000,1.000000,0.200000
// JZ,0.800000
// J3,0.000000,0.000000,0.800000
// '
// 'Turning router OFF
// C7
// END
// '
// '
// UNIT_ERROR:
// CN, 91                            'Run file explaining unit error
// END

// `;

const template = (x: string, y: string, offset: string) =>
	`

'VECTRIC POST REVISION
'90F96787DA0D140DD9CF843C14DAE4D8
'----------------------------------------------------------------
'SHOPBOT ROUTER FILE IN INCHES
'GENERATED BY PARTWorks
'Minimum extent in X = 0.000 Minimum extent in Y = 0.000 Minimum extent in Z = -1.000
'Maximum extent in X = 12.500 Maximum extent in Y = 6.625 Maximum extent in Z = 0.000
'Length of material in X = 12.500
'Length of material in Y = 6.625
'Depth of material in Z = 1.000
'Home Position Information = Bottom Left Corner, Material Surface 
'Home X = 0.000000 Home Y = 0.000000 Home Z = 0.800000
'Rapid clearance gap or Safe Z = 0.200
'UNITS:Inches
'
IF %(25)=1 THEN GOTO UNIT_ERROR	'check to see software is set to standard
SA                             	'Set program to absolute coordinate mode
CN, 90
'New Path
'Toolpath Name = Profile 1 [1]
'Tool Name   = Ball Nose (1/2")

&PWSafeZ = 0.200
&PWZorigin = Material Surface
&PWMaterial = 1.000
'&ToolName = "Ball Nose (1/2")"
&Tool =8           'Tool number to change to
C9                   'Change tool
TR,11000               'Set spindle RPM
C6                   'Spindle on
PAUSE 2
'
MS,0.7,0.125
JZ,0.800000
J3,${offset},${offset},0.200000
' M3,${offset},${offset},-0.062500
' M3,${offset},${y},-0.062500
' M3,${x},${y},-0.062500
' M3,${x},${offset},-0.062500
' M3,${offset},${offset},-0.062500
M3,${offset},${offset},-0.125000
M3,${offset},${y},-0.125000
M3,${x},${y},-0.125000
M3,${x},${offset},-0.125000
M3,${offset},${offset},-0.125000
M3,${offset},${offset},-0.187500
M3,${offset},${y},-0.187500
M3,${x},${y},-0.187500
M3,${x},${offset},-0.187500
M3,${offset},${offset},-0.187500
J3,${offset},${offset},0.200000
JZ,0.800000
J3,0.000000,0.000000,0.800000
'
'Turning router OFF
C7
END
'
'
UNIT_ERROR:
CN, 91                            'Run file explaining unit error
END


`;

type Val = [name: string, coords: [x: string, y: string], offset?: string];

const vals: Val[] = [
	// ['a', ['20 1/16', '12']],
	// // ['b', ['19 3/16', '12 1/2']],
	// ['a-1', ['20 1/16', '12'], '1 1/16'],
	// ['a-2', ['20 1/16', '12'], '1 1/8'],
	// ['a-3', ['20 1/16', '12'], '1 3/16'],
	// ['a-4', ['20 1/16', '12'], '1 1/4'],
	// ['a-5', ['20 1/16', '12'], '1 5/16'],
	// ['a-6', ['20 1/16', '12'], '1 3/8'],
	// ['a-7', ['20 1/16', '12'], '1 7/16'],
	// ['a-8', ['20 1/16', '12'], '1 1/2']
	['a', ['15 15/16', '12']],
	['b', ['15 15/16', '12']],
	['c', ['15 15/16', '11 15/16']]
];
const group = 'j';

rmSync(`./group-${group}`, { recursive: true, force: true });
mkdirSync(`./group-${group}`);

for (const [label, [x, y], offset = '1'] of vals) {
	const output = template(
		new Fraction(x).subtract(offset).toDecimal().toFixed(6),
		new Fraction(y).subtract(offset).toDecimal().toFixed(6),
		new Fraction(offset).toDecimal().toFixed(6)
	);

	writeFileSync(`./group-${group}/${label}.sbp`, output, { encoding: 'utf8' });
}
